# Generated by Django 5.2.3 on 2025-06-18 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('center', models.CharField(max_length=100)),
                ('area_manager', models.CharField(max_length=100)),
                ('area_manager_email', models.EmailField(max_length=254)),
                ('vin', models.CharField(max_length=100)),
                ('tele_no', models.CharField(max_length=20)),
                ('complaint_no', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.TextField()),
                ('immediate_action', models.TextField()),
                ('correct_action', models.TextField()),
                ('complaint_type', models.CharField(choices=[('Operation Issue', 'Operation Issue'), ('Customer Care Issue', 'Customer Care Issue'), ('Marketing Issue', 'Marketing Issue'), ('Technical Issue', 'Technical Issue'), ('Bribe Case', 'Bribe Case'), ('Illegal Activities', 'Illegal Activities'), ('Other', 'Other')], max_length=50)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Solved', 'Solved'), ('Rejected', 'Rejected')], max_length=20)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
