# Generated by Django 5.2.3 on 2025-06-18 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('center', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=100)),
                ('previous_class', models.CharField(max_length=100)),
                ('change_class', models.CharField(choices=[('Motor Cycle', 'Motor Cycle'), ('Motor Car', 'Motor Car'), ('Tricycle', 'Tricycle'), ('Dual Purpose', 'Dual Purpose'), ('Motor Lorry', 'Motor Lorry'), ('Motor Coach', 'Motor Coach'), ('Prime Mover', 'Prime Mover'), ('Land Vehicle', 'Land Vehicle'), ('Omni Bus', 'Omni Bus')], max_length=50)),
                ('reason', models.TextField()),
                ('approved_by', models.CharField(choices=[('Nuwan', 'Nuwan'), ('Rasika', 'Rasika'), ('Other', 'Other')], max_length=50)),
                ('refund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
